namespace: felixfontein
name: hosttech_dns
version: 1.1.1
readme: README.md
authors:
  - Felix Fontein (https://github.com/felixfontein)
description: Modules to create, delete and modify DNS entries with the Hosttech DNS API
license_file: COPYING
tags:
  - hosttech
  - dns
dependencies: {}
repository: https://github.com/felixfontein/ansible-hosttech_dns
documentation: https://github.com/felixfontein/ansible-hosttech_dns/tree/main/README.md#included-content
homepage: https://github.com/felixfontein/ansible-hosttech_dns
issues: https://github.com/felixfontein/ansible-hosttech_dns/issues
build_ignore:
  - .gitignore
  - felixfontein-hosttech_dns-*.tar.gz
  - changelogs/.plugin-cache.yaml
  - playground
  - tests/output
  - tests/integration/integration_config.yml
